Person.create(name:'Teru', age:18, mail:'teru@smail')
Person.create(name:'Sumire', age:18, mail:'sumire@smail')
Person.create(name:'Seiko', age:17, mail:'seiko@smail')
Person.create(name:'Takami', age:17, mail:'takami@smail')
Person.create(name:'Awai', age:16, mail:'awai@smail')
